# Flyway
spring.flyway.locations=classpath:db/migration/postgresql

# PostgreSQL (Docker: link-postgres, Port 5556)
spring.datasource.url=jdbc:postgresql://localhost:5556/linkverwaltung
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sven
spring.datasource.password=sven123

# H2 Console deaktiviert
spring.h2.console.enabled=false
