spring.application.name=LinkVerwaltung

# Default-Profil: H2
spring.profiles.active=h2

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true
# Flyway-Location wird im jeweiligen Profil gesetzt

# Security
spring.security.user.name=sven
spring.security.user.password=sven123
