spring.application.name=LinkVerwaltung

# Server
server.port=8080

# Default-Profil: H2
spring.profiles.active=h2

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true
# Flyway-Location wird im jeweiligen Profil gesetzt
